# Exercice 1

In [5]:
# Programme 1
x, y, z = 3.5, 5, 5
z = x / y
p = 7

if (x > 3) and (z * 10 != p):
    print("Blue")
elif (p > y) or (x > 4):
    print("Red")
else:
    print("Black")

Red


In [6]:
# Programme 2

i, j, k = 1, 2, 3
x, y, z = 1.1, 1.2, 1.3

i += x
j += y
k += z

print(i, j, k, x, y, z)

if (i + j) > k and (j - i) == x:
    print("Blue")
else:
    print("Red")


2.1 3.2 4.3 1.1 1.2 1.3
Blue


In [13]:
# Programme 3
def f1(x, y):
    if x < y:
        return 3
    else:
        return 4

def f2(n):
    return 2 * (n - 1)

x = 3.4
y = 5.3
result = f2(f1(x, y))
result

4

# Exercice 2

In [1]:
def diviseur():
    nombre = int(input(" Entrez nombre : "))
    diviseurs = [x for x in range(2,101) if nombre % x == 0]
    return diviseurs
diviseur()

[2, 5, 10]

# Exercice 3

In [2]:
def polynome(x):
    return x**3 - (10*x**2) - (2610*x) + 84

def plus_petite_valeur():
    res = [polynome(x) for x in range(-50, 51)]
    # optionnel
    index = res.index(min(res))
    x_min = index - 50
    return min(res), x_min,

plus_petite_valeur()


(-60999, 33)

# Exercice 4

In [44]:
personne_bday = {'marc': 12, 'marie': 1, 'rosie':12}

3

In [104]:
def anniverssaires(dico, mois):
    personnes = []
    for nom, valeur in dico.items():
        if valeur == mois:
            personnes.append(nom)
    return(personnes)

anniverssaires(personne_bday, 12)

[]

# Exercice 5 

In [97]:
import random           
import numpy as np      

taille = 10
tableau = np.zeros((taille, taille), dtype=int)

nombre_mines = 5
for _ in range(nombre_mines):
    x, y = np.random.randint(0, taille, size=2)
    tableau[x, y] = 1  

In [98]:
tableau

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [99]:
def nombre_mines_adjacentes(taille , tab):
    nb_lignes, nb_colonnes = len(tab), len(tab[0])
    compte_mines = np.zeros((taille, taille), dtype=int)
    # ou 
    # compte_mines = np.zeros_like(tab)

    for i in range(nb_lignes):
        for j in range(nb_colonnes):
            # case actuelle 
            
            # Parcourir les 8 cases autour de la case actuelle
            for x in range(max(0, i-1), min(i+2, nb_lignes)):
                for y in range(max(0, j-1), min(j+2, nb_colonnes)):
                    if tab[x][y] == 1: # si une mine ajout à la position de la case actuelle
                        compte_mines[i][j] += 1 

    return compte_mines
print(nombre_mines_adjacentes(10, tableau))


[[1 1 1 0 0 0 0 1 1 1]
 [1 1 1 0 0 0 0 1 1 1]
 [1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 0 1 2 2]
 [0 0 0 0 0 0 0 1 2 2]
 [0 0 0 0 1 1 1 0 1 1]
 [0 0 0 0 1 1 1 0 0 0]
 [0 0 0 0 1 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


# Exercice 6

In [79]:
VALEURS = {
'A' : 1, 'B' : 3, 'C' : 3, 'D' : 2, 'E' : 1, 'F' : 4, 'G' : 2, 'H' : 4,
'I' : 1, 'J' : 8, 'K' : 10, 'L' : 1, 'M' : 2, 'N' : 1, 'O' : 1, 'P' : 3,
'Q' : 8, 'R' : 1, 'S' : 1, 'T' : 1, 'U' : 1, 'V' : 4, 'W' : 10, 'X' : 10,
'Y' : 10, 'Z' : 10
}

In [105]:
def score_scrabble(mot, grille):
    score = 0
    mot = mot.upper()
    for lettre in mot:
        score += grille[lettre]
    return score


score_scrabble("KAYAK", VALEURS), score_scrabble("INFORMATIQUE", VALEURS ) 

(32, 23)