Exercice 1 :

Pour chacun des programmes suivants, donnez les valeurs de chaque variable à la fin de l’exécution du programme, et indiquez ce qui s’affiche.

In [1]:
x, y=3.5, 5
z = x/y
p=7 

if (x>3) and (z*10!=p):
    print("Blue")
elif (p>y)or(x>4):
    print("Red")
else:
    print("Black")

Red


Valeurs de chaque variable :
x, y=3.5, 5
z= x/y
p=7

Le premier programme renvoie "Red".

In [3]:
i, j, k=1, 2, 3
x, y, z=1.1, 1.2, 1.3
i=i+x
j=j+y
k=k+z
print(i, j, k, x, y, z)
if (i+j>k) and (j-i==x):
    print("Blue")
else:
    print("Red")

2.1 3.2 4.3 1.1 1.2 1.3
Blue


Valeur de chaque variable :
i, j, k=1,2,3


Le deuxième programme renvoie les valeurs de "i, j, k, x, y, z" et "Blue".

In [4]:
def f1(x,y):
    if (x<y):
        return 3
    else:
        return 4
    
def f2(n):
    return 2*n-1

x=3.4
y=5.3
print(f2(f1(y,x)))

7


Le troisième programme renvoie le chiffre "7"

Exercice 2 :

Écrivez une fonction qui permet de trouver tous les diviseurs d'un nombre "n" entre 2 et 100.
- Le programme doit demander à l'utilisateur d'entrer un nombre entier naturel "n".
- Une fois le nombre saisi, le programme renvoie tous les diviseurs de "n" dans une liste.

In [39]:
def trouver_diviseurs(n):
    diviseurs = [i for i in range(2, 100) if n % i == 0]
    return diviseurs 

nombre = int(input("Entrez un nombre entier naturel : "))
resultat = trouver_diviseurs(nombre)

print(f"Les diviseurs de {nombre} entre 2 et 100 sont : {resultat}")
    

Les diviseurs de 10 entre 2 et 100 sont : [2, 5, 10]


Exercice 3 :

Soit le polynôme P défini par P = x³– 10x²– 2610x + 84
- Ecrivez une fonction qui, étant donné un entier naturel x, retourne la valeur de ce polynôme pour x.
- Ecrivez un programme qui affiche la plus petite valeur prise par ce polynôme pour les entiers appartenant à l’intervalle [−50, 50].

In [50]:
def trouver_polynome(x):
    return x**3 - 10*x**2 - 2610*x + 84

valeur_polynome = [trouver_polynome(i) for i in range (-50, 50)]
plus_petite_valeur = min(valeur_polynome)

print(f"La plus petite valeur du polynome dans l'intervalle [-50, 50] est : {plus_petite_valeur}")


La plus petite valeur du polynome dans l'intervalle [-50, 50] est : -60999


Exercice 4 :

Créez une structure de données dans lequel :
- les clés sont les prénoms de différentes personnes. (Il n'y a aucun prénom en double)
- les valeurs sont les mois de naissance de ces personnes stockées sous forme de nombres entiers (1 pour
janvier, ... 12 pour décembre)

Vous devez écrire une fonction anniversaire prenant en arguments le dictionnaire créer ci-dessus ainsi qu'un numéro d'un mois et renvoyant une liste contenant les prénoms des personnes nées durant ce mois.

In [8]:
import pandas as pd 

data = {
    'Prénoms' : ['Jean', 'Jeanne', 'Fernand', 'Monique', 'Stéphane', 'Jean-Claude'],
    'Mois de Naissance' : [3, 2, 10, 1, 2, 4]
}

personnes = pd.DataFrame(data)
personnes

Prénoms  Mois de Naissance
0         Jean                  3
1       Jeanne                  2
2      Fernand                 10
3      Monique                  1
4     Stéphane                  2
5  Jean-Claude                  4

In [10]:
anniversaire_fevrier = personnes[personnes['Mois de Naissance'] == 2]
anniversaire_fevrier

Prénoms  Mois de Naissance
1    Jeanne                  2
4  Stéphane                  2

Exercice 5 :
Développer une version simplifiée du jeu de démineur en utilisant Python.

Étape 1: Initialisation du Champ de Mines

Créer une grille 2D pour représenter le champ de mines. Chaque cellule peut être une mine (*) ou non (0). Utilisez
une taille de grille prédéfinie (par exemple, 10x10) et un nombre fixe de mines. Placez les mines de manière
aléatoire.

Étape 2: Calcul des Mines Adjacentes

Écrire une fonction qui, pour chaque cellule, calcule le nombre de mines dans les cellules adjacentes (les cellules
autour d’une case) et leur position. Faites attention aux bords de la grille pour éviter les erreurs d'indexation.

In [40]:
import numpy as np
import random

def generer_champ_de_mines(): 
    #test
    mines = np.random.choice(np.arange(0, 33), size=(10, 10))
    #comment mettre un asterix ?
    return mines

champ_de_mines = generer_champ_de_mines()

print(champ_de_mines)

[[ 2 16  8 24 10 27 13 17  4 11]
 [19  0 17 30 15 17 26 13 19 14]
 [31 30 18  4  6 12 20 28 18 18]
 [ 6  6 22 14 23 17  2 24 11 25]
 [ 2  1 10 25 20  4 16 27 10 11]
 [ 3  1 15 15 25 30  9 27 21  9]
 [28 24 20 22 15 26 11  7  4  4]
 [15  6 16 17 14 23 14  9  5 32]
 [22  1  3 28 32 11  3  4 16 30]
 [11 15 12 32  6  9 26  3 24  2]]
